### ISSUE TITLE
Problem with ZEIT deploy

### ISSUE THREAD

**Issue by daimonkor** [colyseus/colyseus-examples#16]
Please fix now.json file, does not work project at ZEIT deployment. Thanks for help.

**Comment by endel** [comment]
can you provide the logs @daimonkor? cheers!

**Comment by daimonkor** [comment]
http://prntscr.com/mkpvlf

**Comment by endel** [comment]
thanks @daimonkor, managed to deploy now using `"version": 2` on `now.json` file: https://colyseus-examples-dhbbjzitqb.now.sh/

I've dragged the folder of the project to zeit-now's icon on my desktop, and the deployment was successful. 

Cheers!

**Comment by daimonkor** [comment]
What is my problem? http://prntscr.com/mkqf2c

**Comment by endel** [comment]
@daimonkor that's odd. It seems it didn't recognize it as a node application, and it's trying to download the `index.ts` file.

I've deployed just like this: https://drive.google.com/open?id=15TsVI52yUxfjrbDbz-V4gvSe3WiJ3dNd

Don't really know what's going wrong there :(

**Comment by daimonkor** [comment]
Magic, the same state http://prntscr.com/mkqjgk http://prntscr.com/mkqjr7 . Official application, downloaded today

**Comment by paulogdm** [comment]
With the current `now.json`, without `"builds"`, it is deploying as static.
Do notice that our current Now 2.0 still doesn't support WSS, which is needed for this repository, if I understand it correctly.
Please @daimonkor, take a look at our [examples](https://github.com/zeit/now-examples) before deploying.

**Comment by daimonkor** [comment]
But I saw worked sample https://drive.google.com/open?id=15TsVI52yUxfjrbDbz-V4gvSe3WiJ3dNd ). What is the magic. Client used ws

**Comment by endel** [comment]
@daimonkor I can reproduce your issue using `now` from the command-line. I'll follow @paulogdm's suggestion and will update the repository as soon as I get it working

**Comment by daimonkor** [comment]
@endel Thank you very much

**Comment by endel** [comment]
@daimonkor apparently now `v2` still doesn't support WebSockets (as @paulogdm mentioned, and I thought it was only for Secure WebSockets 😅)

I've changed the `now.json` file to use `v1` instead, which I've managed to deploy successfully from the command-line!

Let me know if it works for you @daimonkor

**Comment by daimonkor** [comment]
@endel I tested http://prntscr.com/mkslb9. Used node module now  Now CLI 13.1.3.

**Comment by endel** [comment]
@daimonkor that's odd, here the command-line asks me if you'd like to proceed, and then it deploys sucessfully

![screenshot 2019-02-13 at 21 22 20](https://user-images.githubusercontent.com/130494/52751118-76d94200-2fd5-11e9-8c12-f6465696a64a.png)

**Comment by daimonkor** [comment]
@endel Version number are common, but they are different releases.

**Comment by endel** [comment]
thanks @daimonkor, I guess I can deploy because my account may be older than yours, it's a shame they're disabling V1 for new users, given that V2 doesn't even support WebSockets yet. 😢

**Comment by daimonkor** [comment]
Still waiting support)

**Comment by endel** [comment]
I'm afraid it will take long for them to support environments with WebSockets, you'd be better off using Heroku or a VPS, they support tickets about this are months old

**Comment by daimonkor** [comment]
@endel I will try use Heroku, thanks

**Comment by endel** [comment]
Zeit is not listed anymore as a deployment target due to how their new system works
